// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlf54f9894IwddBMBzklnxoTuS1Sj1_qk',
    appId: '1:40704136538:web:eb9f12795dae7a4a5c8f63',
    messagingSenderId: '40704136538',
    projectId: 'product-catalogue-zyne',
    authDomain: 'product-catalogue-zyne.firebaseapp.com',
    storageBucket: 'product-catalogue-zyne.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbiDzrlbaqrrofkRQr0kIcSOYqM3bzXTA',
    appId: '1:40704136538:android:5141e3727ddc69a05c8f63',
    messagingSenderId: '40704136538',
    projectId: 'product-catalogue-zyne',
    storageBucket: 'product-catalogue-zyne.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAydoBK0-MDaRiMyi60FkfC3OVWIVen5Ls',
    appId: '1:40704136538:ios:230868aa50363a555c8f63',
    messagingSenderId: '40704136538',
    projectId: 'product-catalogue-zyne',
    storageBucket: 'product-catalogue-zyne.firebasestorage.app',
    iosBundleId: 'com.rzjaffery.productCatalogue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAydoBK0-MDaRiMyi60FkfC3OVWIVen5Ls',
    appId: '1:40704136538:ios:230868aa50363a555c8f63',
    messagingSenderId: '40704136538',
    projectId: 'product-catalogue-zyne',
    storageBucket: 'product-catalogue-zyne.firebasestorage.app',
    iosBundleId: 'com.rzjaffery.productCatalogue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlf54f9894IwddBMBzklnxoTuS1Sj1_qk',
    appId: '1:40704136538:web:06d8a3ac6d4d21935c8f63',
    messagingSenderId: '40704136538',
    projectId: 'product-catalogue-zyne',
    authDomain: 'product-catalogue-zyne.firebaseapp.com',
    storageBucket: 'product-catalogue-zyne.firebasestorage.app',
  );
}
