// lib/main.dart
// App entry point:
//   1. Initialises Firebase
//   2. Registers Providers
//   3. Uses AuthWrapper to route between Login and Home screens

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';

import 'firebase_options.dart';           // Generated by FlutterFire CLI
import 'providers/auth_provider.dart';
import 'providers/product_provider.dart';
import 'screens/auth/login_screen.dart';
import 'screens/product/home_screen.dart';
import 'utils/app_theme.dart';

void main() async {
  // Ensure Flutter engine is ready before calling native code
  WidgetsFlutterBinding.ensureInitialized();

  // Initialise Firebase using the generated configuration file
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        // AuthProvider listens to Firebase auth state changes globally
        ChangeNotifierProvider(create: (_) => AuthProvider()),
        // ProductProvider manages the product list and pagination
        ChangeNotifierProvider(create: (_) => ProductProvider()),
      ],
      child: MaterialApp(
        title: 'Product Manager',
        debugShowCheckedModeBanner: false,
        theme: AppTheme.theme,
        home: const AuthWrapper(),
      ),
    );
  }
}

// ── AuthWrapper ────────────────────────────────────────────────────────────────
// Listens to AuthProvider and automatically switches between
// LoginScreen (unauthenticated) and HomeScreen (authenticated).
class AuthWrapper extends StatelessWidget {
  const AuthWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    final auth = context.watch<AuthProvider>();

    if (auth.isAuthenticated) {
      return const HomeScreen();
    }
    return const LoginScreen();
  }
}